apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-pg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-pg
  template:
    metadata:
      labels:
        app: jobs-pg
    spec:
      containers:
        - name: jobs-pg
          image: postgres:latest
          resources:
            limits:
              memory: "1024Mi"
              cpu: "0.2"
            requests:
              memory: "100Mi"
              cpu: "0.1"
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-pg-srv
spec:
  selector:
    app: jobs-pg
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432