apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-depl
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: 'bitnami/zookeeper:latest'
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: 'yes'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-srv
  labels:
    app: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
          - name: KAFKA_BROKER_ID 
            value: '0'
          - name: ALLOW_PLAINTEXT_LISTENER 
            value: 'yes'
          - name: KAFKA_ADVERTISED_LISTENERS 
            value: PLAINTEXT://127.0.0.1:9092
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT 
            value: zookeeper-srv:2181
          - name: KAFKA_ADVERTISED_HOST 
            value: localhost
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    protocol: TCP
  selector:
    app: kafka-depl