name: test-jobs

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'Jobs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 18
          cache: maven
      - name: Build with Maven
        run: mvn clean install package
        working-directory: Common

      - name: Run tests
        run: mvn clean install compile test
        working-directory: ./Jobs

      - name: Check Production tests
        run: docker build . -f Users/Dockerfile
