name: test-jobs

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'Jobs/**'
      - 'config/**'
  push:
    branches:
      - dev
    paths:
      - 'Jobs/**'
      - 'config/**'
env:
  REGISTRY_NAME: serviceregistryjobagggregator
  APP_NAME: users

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 18
          cache: maven
      - name: Build with Maven
        run: mvn clean install package
        working-directory: Common

      - name: Run tests
        run: mvn clean install compile test
        working-directory: ./Jobs

      - name: Build docker image
        run: docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }} -f Jobs/Dockerfile

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Deploy to minikube
        run: |
          kubectl apply -f configs/k8s/dev/jobs_pg_depl.yaml
          kubectl apply -f configs/k8s/dev/jobs_depl.yaml
