name: test-users

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'Users/**'
      - 'config/**'
  push:
    branches:
      - dev
    paths:
      - 'Users/**'
      - 'config/**'
env:
  REGISTRY_NAME: serviceregistryjobagggregator
  APP_NAME: users

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 18
          cache: maven
      - name: Build with Maven
        run: mvn clean install package
        working-directory: Common
        
      - name: Run tests
        run: ./mvnw clean install compile test
        working-directory: ./Users

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Build docker image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }} -f Users/Dockerfile

      - name: Deploy to minikube
        run: |
          kubectl apply -f configs/k8s/dev/users_pg_depl.yaml
          kubectl apply -f configs/k8s/dev/users_depl.yaml

